name: Test & Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn lint
      - run: yarn build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: build'
